#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 and fizz buzz
a=1
while ((a <= 100)); do
    if (( a % 3 == 0  && a % 5 == 0 )); then
	echo "FizzBuzz"
    elif ((a % 3 == 0)); then
	echo "Fizz"
    elif ((a % 5 == 0)); then
	echo "Buzz"
    else
	echo $a
    fi
    ((a++))
done
