#!/usr/bin/env bash
# This script is displaying "Holberton School" "bad luck" and "good luck"
a=1
while [ $a -lt 11 ]; do
    if [ $a -eq 4 ]; then
	echo "bad luck"
    elif [ $a -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((a++))
done
