#!/usr/bin/env bash
# This script is displaying 20 numbers and "bad luck from China"
# "bad luck from Japan" "bad luck from Italy"
a=1
while (( a <= 20 )); do
    echo $a
    case $a in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    ((a++))
done
